# Generated by Django 4.2.13 on 2024-06-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_companies_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="companies",
            name="website",
            field=models.URLField(default="https://www.google.com/"),
        ),
    ]
